# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Clazz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('token', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('create_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyStoneBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('create_time', models.IntegerField(default=0)),
                ('info', models.CharField(default='', max_length=32)),
                ('detail', models.CharField(default='', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='InterestTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enname', models.CharField(default='', max_length=128)),
                ('chname', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='InterestTagContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enname', models.CharField(default='', max_length=128)),
                ('chname', models.CharField(default='', max_length=128)),
                ('category', models.CharField(default='', max_length=32)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.InterestTag')),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=1024)),
                ('create_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MessageSender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_url', models.CharField(default='', max_length=32)),
                ('name', models.CharField(default='', max_length=128)),
                ('mark', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneVerify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=8)),
                ('sent_time', models.IntegerField(default=0)),
                ('verify_time', models.IntegerField(default=0)),
                ('sms_type', models.CharField(default='', max_length=16)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('usage', models.CharField(default='', max_length=32, primary_key=True, serialize=False)),
                ('content', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TodayUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_location_long', models.FloatField(default=0.0)),
                ('verify_location_lat', models.FloatField(default=0.0)),
                ('avatar_url', models.CharField(max_length=512)),
                ('phone', models.CharField(max_length=32)),
                ('nickname', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=32)),
                ('age', models.IntegerField(default=0)),
                ('birthday', models.IntegerField(default=0)),
                ('clazz', models.CharField(max_length=128)),
                ('block_same_class', models.BooleanField(default=True)),
                ('hometown', models.CharField(default='', max_length=128)),
                ('contact', models.CharField(max_length=256)),
                ('love_status', models.CharField(max_length=128)),
                ('prefer_gender', models.CharField(max_length=128)),
                ('introduction', models.CharField(max_length=1024)),
                ('energy_stone', models.IntegerField(default=10)),
                ('password', models.CharField(max_length=256)),
                ('pw_salt', models.CharField(max_length=128)),
                ('signup_time', models.IntegerField(default=0)),
                ('signup_ua', models.CharField(max_length=256)),
                ('signup_ip', models.CharField(max_length=32)),
                ('signin_time', models.IntegerField(default=0)),
                ('signin_ua', models.CharField(max_length=256)),
                ('signin_ip', models.CharField(max_length=32)),
                ('region', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserInterestTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='backend.InterestTagContent')),
                ('tag', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='backend.InterestTag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserMeet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_meet_other', to='backend.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
                ('altitude', models.FloatField(default=0.0)),
                ('floor', models.IntegerField(default=0)),
                ('horizontal_accuracy', models.FloatField(default=0.0)),
                ('vertical_accuracy', models.FloatField(default=0.0)),
                ('speed', models.FloatField(default=0.0)),
                ('heading', models.FloatField(default=0.0)),
                ('timestamp', models.IntegerField(default=0)),
                ('create_time', models.IntegerField(default=0)),
                ('location_name', models.CharField(default='', max_length=512)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
            ],
        ),
        migrations.AddField(
            model_name='usermeet',
            name='other_pos',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='user_meet_other_pos', to='backend.UserPosition'),
        ),
        migrations.AddField(
            model_name='usermeet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_meet_user', to='backend.User'),
        ),
        migrations.AddField(
            model_name='usermeet',
            name='user_pos',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='user_meet_user_pos', to='backend.UserPosition'),
        ),
        migrations.AddField(
            model_name='todayuser',
            name='other',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='today_user_other', to='backend.User'),
        ),
        migrations.AddField(
            model_name='todayuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='today_user_user', to='backend.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='backend.MessageSender'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
        ),
        migrations.AddField(
            model_name='energystonebill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
        ),
        migrations.AddField(
            model_name='clazz',
            name='major',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.Major'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.Province'),
        ),
    ]
