# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-13 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20161013_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area_num',
            field=models.IntegerField(default=-1),
        ),
    ]
