# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-13 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_user_area_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signin_time',
            field=models.CharField(default='2016-10-13 21:14:29', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='signup_time',
            field=models.CharField(default='2016-10-13 21:14:29', max_length=32),
        ),
        migrations.AlterField(
            model_name='usermeet',
            name='meet_time',
            field=models.CharField(default='2016-10-13 21:14:29', max_length=32),
        ),
    ]
