# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-13 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20161013_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='usermeet',
            name='meet_time',
            field=models.CharField(default='2016-10-13 23:34:33', max_length=32),
        ),
    ]
