# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-16 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20161013_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='department',
        ),
        migrations.RemoveField(
            model_name='clazz',
            name='major',
        ),
        migrations.AddField(
            model_name='clazz',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.Department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='category',
            field=models.CharField(choices=[('东校区', '东校区'), ('主校区', '主校区')], max_length=32),
        ),
        migrations.AlterField(
            model_name='usermeet',
            name='meet_time',
            field=models.CharField(default='2016-10-16 20:54:55', max_length=32),
        ),
        migrations.DeleteModel(
            name='Major',
        ),
    ]
