# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-16 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20161016_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interesttagcontent',
            name='category',
            field=models.CharField(choices=[('东校区', '东校区'), ('主校区', '主校区')], max_length=32),
        ),
        migrations.AlterField(
            model_name='usermeet',
            name='meet_time',
            field=models.CharField(default='2016-10-16 21:00:19', max_length=32),
        ),
    ]
