# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-19 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20161016_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeet',
            name='meet_time',
            field=models.CharField(default='2016-10-19 11:13:22', max_length=32),
        ),
    ]
