# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-19 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20161019_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeet',
            name='meet_distance',
            field=models.IntegerField(default=0, verbose_name='相遇距离'),
        ),
        migrations.AlterField(
            model_name='usermeet',
            name='area_num',
            field=models.IntegerField(default=-1, verbose_name='区域编号'),
        ),
        migrations.AlterField(
            model_name='usermeet',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='usermeet',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='usermeet',
            name='meet_place',
            field=models.CharField(default='', max_length=32, verbose_name='相遇地点'),
        ),
        migrations.AlterField(
            model_name='usermeet',
            name='meet_time',
            field=models.CharField(default='2016-10-19 12:27:18', max_length=32, verbose_name='相遇时间'),
        ),
    ]
