# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-19 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20161019_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(default=0.0, verbose_name='经度')),
                ('latitude', models.FloatField(default=0.0, verbose_name='纬度')),
                ('area_num', models.IntegerField(default=-1, verbose_name='区域编号')),
                ('meet_place', models.CharField(default='', max_length=32, verbose_name='相遇地点')),
                ('create_time', models.CharField(default='2016-10-19 15:26:59', max_length=32, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User', verbose_name='主用户')),
            ],
        ),
        migrations.AlterField(
            model_name='usermeet',
            name='meet_time',
            field=models.CharField(default='2016-10-19 15:26:59', max_length=32, verbose_name='相遇时间'),
        ),
    ]
