# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-19 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20161019_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeet',
            name='meet_time',
            field=models.CharField(default='2016-10-19 15:36:50', max_length=32, verbose_name='相遇时间'),
        ),
        migrations.AlterField(
            model_name='userposition',
            name='create_time',
            field=models.CharField(default='2016-10-19 15:36:50', max_length=32, verbose_name='创建时间'),
        ),
    ]
