# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-22 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20161019_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermeet',
            old_name='meet_place',
            new_name='location_name',
        ),
        migrations.RenameField(
            model_name='userposition',
            old_name='meet_place',
            new_name='location_name',
        ),
        migrations.AlterField(
            model_name='usermeet',
            name='meet_time',
            field=models.CharField(default='2016-10-22 19:38:34', max_length=32, verbose_name='相遇时间'),
        ),
        migrations.AlterField(
            model_name='userposition',
            name='create_time',
            field=models.CharField(default='2016-10-22 19:38:34', max_length=32, verbose_name='创建时间'),
        ),
    ]
