# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-26 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20161022_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeethistory',
            name='fate',
            field=models.IntegerField(default=0, verbose_name='缘分值'),
        ),
        migrations.AddField(
            model_name='usermeethistory',
            name='matching',
            field=models.IntegerField(default=0, verbose_name='匹配度'),
        ),
        migrations.AddField(
            model_name='userposition',
            name='leave_time',
            field=models.CharField(max_length=32, null=True, verbose_name='离开时间'),
        ),
        migrations.AlterField(
            model_name='usermeet',
            name='meet_time',
            field=models.CharField(default='2016-10-26 22:35:44', max_length=32, verbose_name='相遇时间'),
        ),
        migrations.AlterField(
            model_name='usermeet',
            name='other',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_meet_other', to='backend.User', verbose_name='相遇用户'),
        ),
        migrations.AlterField(
            model_name='usermeethistory',
            name='meet_num',
            field=models.IntegerField(default=0, verbose_name='相遇次数'),
        ),
        migrations.AlterField(
            model_name='usermeethistory',
            name='other',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_meet_other_history', to='backend.User', verbose_name='相遇用户'),
        ),
        migrations.AlterField(
            model_name='usermeethistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_meet_user_history', to='backend.User', verbose_name='主用户'),
        ),
        migrations.AlterField(
            model_name='userposition',
            name='create_time',
            field=models.CharField(default='2016-10-26 22:35:44', max_length=32, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userposition',
            name='location_name',
            field=models.CharField(default='', max_length=32, verbose_name='地点名称'),
        ),
    ]
