# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-02 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20161027_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeet',
            name='meet_time',
            field=models.CharField(default='2016-11-02 21:03:09', max_length=32, verbose_name='相遇时间'),
        ),
        migrations.AlterField(
            model_name='userposition',
            name='create_time',
            field=models.CharField(default='2016-11-02 21:03:09', max_length=32, verbose_name='创建时间'),
        ),
    ]
